name: Pubblicazione Pagina Prime Pagine

on:
  schedule:
    # 05:00 UTC = 07:00 ora italiana (Legale CEST)
    - cron: '0 5 * * *'
    # 18:00 UTC = 20:00 ora italiana (Legale CEST)
    - cron: '0 18 * * *'
  workflow_dispatch: # Mantiene la possibilità di avviarlo a mano quando desideri

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configurazione Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installazione dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Esecuzione dello script prime_pagine.py
        env:
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
          BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
        run: python prime_pagine.py
